name: Update My Biss File
on:
  workflow_dispatch: # زرار للتشغيل اليدوي
  schedule:
    - cron: '0 */6 * * *' # يشتغل لوحده كل 6 ساعات

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requests
        run: pip install requests

      - name: Run Update Script
        run: python update_codes.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add biss
          git commit -m "Auto Update Biss" || exit 0
          git push
