name: Forme

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # تحديث لـ v4

      - name: Set up Python
        uses: actions/setup-python@v5 # تحديث لـ v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python Forme.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add last_keys_list.txt || echo "No changes"
          git commit -m "Update keys" || echo "No changes"
          git push || echo "No changes"
