name: Forme
on:
  schedule:
    - cron: '0 * * * *' # هيشتغل لوحده كل ساعة
  workflow_dispatch: # زرار تشغيل يدوي

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        run: python Forme.py # تم تعديل الحرف لـ m صغيرة ليطابق اسم ملفك
