- name: Run Scraper
      run: python keys.py

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # السطر ده بيحدث الملف لو موجود أو بيكريهه لو مش موجود
        git add keys.json 
        # الـ || exit 0 عشان لو مفيش تغييرات الأكشن ميفشلش
        git commit -m "Update keys" || exit 0
        git push
